package com.agents.app.data

import android.content.Context
import android.util.Log
import com.agents.app.models.ProjectScaffold
import java.io.File

class ProjectFileWriter(private val context: Context) {

    fun writeProjectFiles(projectId: String, projectName: String, scaffold: ProjectScaffold) {
        try {
            val projectPath = getProjectPath(projectId)

            // 1. ARCHITECTURE.md
            writeArchitectureFile(projectPath, scaffold)

            // 2. ROADMAP.md
            writeRoadmapFile(projectPath, scaffold)

            // 3. RULES.md
            writeRulesFile(projectPath, scaffold)

            // 4. SKILLS.md
            writeSkillsFile(projectPath, scaffold)

            // 5. AGENTS.md (incl. SKILLS.md Referenz)
            writeAgentsFile(projectPath, scaffold)

            // 6. Update diary.md
            updateDiary(projectPath, scaffold)

            Log.d("ProjectFileWriter", "Alle Dateien erfolgreich geschrieben fuer Projekt: $projectName")
        } catch (e: Exception) {
            Log.e("ProjectFileWriter", "Fehler beim Schreiben von Dateien: ${e.message}")
        }
    }

    private fun writeArchitectureFile(projectPath: String, scaffold: ProjectScaffold) {
        val content = """
            # ARCHITECTURE

            ## Project Overview
            **Domain:** ${scaffold.discoveryContext.domain}
            **Technologies:** ${scaffold.discoveryContext.technologies.joinToString(", ")}
            **Experience Level:** ${scaffold.discoveryContext.experienceLevel}
            **Project Size:** ${scaffold.discoveryContext.projectSize}

            ## Concerns & Constraints
            ${scaffold.discoveryContext.concerns.joinToString("\n") { "- $it" }}

            ## Architecture
            ${scaffold.architecture}

            ## Technology Stack
            ${scaffold.discoveryContext.technologies.joinToString("\n") { "- $it" }}

            ## Key Design Decisions
            - Modular architecture fuer skalierbare Entwicklung
            - Separation of concerns (UI, Business Logic, Data)
            - Testing auf allen Ebenen

            ## Non-Goals
            - Performance-Optimierung vor Funktionalitaet
            - Microservices-Komplexitaet (nicht notwendig)
            - Premature Abstraction

            ---
            *Generated by Architect Agent - ${System.currentTimeMillis()}*
        """.trimIndent()

        File("$projectPath/ARCHITECTURE.md").writeText(content)
    }

    private fun writeRoadmapFile(projectPath: String, scaffold: ProjectScaffold) {
        val phasesContent = scaffold.phases.joinToString("\n\n") { phase ->
            """
            ## Phase ${phase.phaseNumber}: ${phase.name}

            **Duration:** ${phase.duration}
            **Focus:** ${phase.focus}

            ${phase.description}

            ### Key Deliverables
            - [TODO] Implement ${phase.focus}
            - [TODO] Write tests
            - [TODO] Documentation
            """.trimIndent()
        }

        val content = """
            # ROADMAP

            ## Overview
            Diese Roadmap teilt das Projekt in ${scaffold.phases.size} Phasen auf.
            Jede Phase ist in sich geschlossen und kann separat delivered werden.

            $phasesContent

            ## Dependencies
            - Phase 1 muss vor Phase 2 abgeschlossen sein
            - Phase 2 muss vor Phase 3 abgeschlossen sein

            ## Success Criteria
            - Alle Phasen abgeschlossen
            - Alle Tests gruen
            - Dokumentation aktuell

            ---
            *Generated by Architect Agent - ${System.currentTimeMillis()}*
        """.trimIndent()

        File("$projectPath/ROADMAP.md").writeText(content)
    }

    private fun writeRulesFile(projectPath: String, scaffold: ProjectScaffold) {
        val rulesContent = scaffold.rules.mapIndexed { index, rule ->
            "${index + 1}. $rule"
        }.joinToString("\n")

        val content = """
            # RULES

            Regeln fuer die Entwicklung dieses Projekts.
            Diese Regeln sichern Qualitaet, Konsistenz und Wartbarkeit.

            ## Development Guidelines

            $rulesContent

            ## Code Quality
            - Aller Code muss getestet sein (min. 70% coverage)
            - Code Reviews muessen durchgefuehrt werden
            - Linting muss green sein
            - Keine TODO-Comments ohne Issue-Link

            ## Commit Standards
            - Commit-Messages sind sprechend und beschreibend
            - Max 1 Feature pro Commit
            - Keine "WIP" Commits in main

            ## Testing
            - Unit Tests fuer Business Logic
            - Integration Tests fuer APIs
            - Manual Testing fuer UI

            ---
            *Generated by Architect Agent - ${System.currentTimeMillis()}*
        """.trimIndent()

        File("$projectPath/RULES.md").writeText(content)
    }

    private fun writeSkillsFile(projectPath: String, scaffold: ProjectScaffold) {
        val content = """
            # SKILLS

            ## Available Skills

            Diese Skills stehen den Agenten in diesem Projekt zur Verfuegung.
            Sie werden durch den System Prompt jedes Agenten aktiviert.

            ## Core Skills

            ### Code-Generierung
            - **kotlin-idioms-refactor**: Analysiert und optimiert Kotlin-Code
            - **compose-ui-generator**: Erstellt moderne Compose UIs
            - **room-database-engineer**: Verwaltet lokale Persistenz mit Room
            - **kotlin-coroutines-flow**: Entwickelt asynchrone Ablaeufe

            ### Architektur
            - **android-architecture-builder**: MVVM/MVI/Repository Pattern
            - **material3-theme-generator**: Material Design 3 Themes
            - **compose-navigation-manager**: Typ-sichere Navigation

            ### Qualitaet
            - **compose-performance-optimizer**: Recomposition-Analyse
            - **github-actions-android-ci**: Automatisierte Builds
            - **github-pr-assistant**: Code-Review-Unterstuetzung

            ### Integration
            - **android-background-tasks**: WorkManager, Services
            - **android-local-ai-integration**: On-Device Inferenz (LiteRT)

            ## Activation
            Skills werden NICHT automatisch geladen. Jeder Agent muss
            in seinem System Prompt explizit referenzieren, welche Skills
            aktiviert werden sollen.

            Beispiel:
            ```
            Aktiviere folgende Skills: kotlin-idioms-refactor,
            compose-ui-generator, room-database-engineer
            ```

            ---
            *Generated by Architect Agent - ${System.currentTimeMillis()}*
        """.trimIndent()

        File("$projectPath/SKILLS.md").writeText(content)
    }

    private fun writeAgentsFile(projectPath: String, scaffold: ProjectScaffold) {
        val agentsContent = scaffold.suggestedAgents.mapIndexed { index, agent ->
            """
            ## Agent ${index + 1}: ${agent.name}

            **Description:** ${agent.description}
            **Provider:** ${agent.provider}
            **Model:** ${agent.model}
            **Temperature:** ${agent.temperature}

            ### System Prompt
            ${agent.systemPrompt}
            """.trimIndent()
        }.joinToString("\n\n")

        val content = """
            # AGENTS

            ## Overview
            Diese Agenten sind spezialisiert auf die Anforderungen dieses Projekts.
            Sie arbeiten zusammen, um die Phasen umzusetzen.

            $agentsContent

            ## Agent Conventions
            - Jeder Agent hat eine Spezialisierung
            - Agenten koennen zusammen arbeiten (Multi-Agent Sessions)
            - Jeder Agent hat einen klaren System Prompt
            - Prompts koennen in Settings angepasst werden

            Weitere Details in SKILLS.md im Projekt-Root.

## Best Practices
            - Start mit dem "Architect" fuer Fragen zur Struktur
            - Nutze spezialisierte Agenten fuer Domain-Fragen
            - Session-Logs sind in diary.md verfuegbar

            ---
            *Generated by Architect Agent - ${System.currentTimeMillis()}*
        """.trimIndent()

        File("$projectPath/AGENTS.md").writeText(content)
    }

    private fun updateDiary(projectPath: String, scaffold: ProjectScaffold) {
        val diaryFile = File("$projectPath/diary.md")
        val dateStr = java.text.SimpleDateFormat("yyyy-MM-dd HH:mm", java.util.Locale.getDefault()).format(java.util.Date())

        val entry = """

            ## Architect Discovery - $dateStr

            ${scaffold.diaryEntry}

            ### Discovery Context
            - Domain: ${scaffold.discoveryContext.domain}
            - Technologies: ${scaffold.discoveryContext.technologies.joinToString(", ")}
            - Level: ${scaffold.discoveryContext.experienceLevel}
            - Size: ${scaffold.discoveryContext.projectSize}

            ### Generated Files
            - ARCHITECTURE.md
            - ROADMAP.md
            - RULES.md
            - AGENTS.md
        """.trimIndent()

        if (diaryFile.exists()) {
            diaryFile.appendText("\n$entry")
        } else {
            diaryFile.writeText("# Project Diary\n$entry")
        }
    }

    private fun getProjectPath(projectId: String): String {
        val projectFolder = File(context.filesDir, "projects")
        val projects = projectFolder.listFiles() ?: emptyArray()
        val projectDir = projects.firstOrNull { it.isDirectory && it.name.endsWith("_$projectId") }
        return projectDir?.absolutePath ?: "$projectFolder/project_$projectId"
    }
}
